### ISSUE TITLE
Preventing block types other than one specified as the default block

### ISSUE THREAD

**Issue by oyeanuj** [GitbookIO/slate-edit-blockquote#3]
Hi folks! Using `slate-edit-list` and `slate-edit-blockquote` in conjunction, I noticed that I could have the list be the block under the `blockquote` node. Is that expected behavior?

I was assuming that only the `typeDefault` would be allowed to be the block node under `blockquote`.

And as always, thank you!

**Comment by Soreine** [comment]
It was designed to be a generic block container. So you should be able to quote anything:

> Quoting a list should be allowed:
> - Just like
> - in Markdown

If you need to enforce the block types in your quotes, you can add a custom schema to your application.
