### ISSUE TITLE
consider refactoring to have plugins be single files?

### ISSUE THREAD

**Issue by ianstormtaylor** [GitbookIO/slate-edit-blockquote#7]
Hey, this is just an idea, and I don't have all the context, so feel free to close. But I think this plugin (and some of the others) being broken apart into many files makes it harder to reason about, and probably harder to maintain. I find that I'm often having to jump between files, remember how options are bound, etc. It adds up to lots of indirection.

I think if this plugin was refactored into a single file, it would end up being 100–200 LOC total, and be really easy to follow exactly what was going on. I'm not sure exactly if it would make using Flow harder, since I have no experience there, but I think it would make everything else much easier.

Just an idea!

Edit: Actually, further research, it would probably end up making the resulting compiled plugin smaller too, and help call out things that could be improved. For example `getSchema` for this plugin returns nothing, and could be removed. And `getCurrentBlockquote` is used in places even though `isSelectionInBlockquote` makes more sense. I feel like some of these types of issues are due to the indirection.

Edit: Even more, it would make things like `wrapInBlockquote` vs. `unwrapBlockquote` not being parallel more obvious too. If they were together, it would be easier to notice it, and even to make a backwards compatible deprecation.

**Comment by Soreine** [comment]
You're right, it could be simplified.
It's just a lot easier to maintain if it follows the same structure than our other plugins. That's the only reason it is made this way.
